name: Create Pull Request

on:
  push

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "PR automatizado"
          title: "PR automatizado para ${{ github.ref_name }}"
          body: |
            Este é um PR automatizado para a branch ${{ github.ref_name }}.
            Revise as mudanças e faça um merge se tudo estiver certo.
          branch: ${{ github.ref_name }}
          base: master
          labels: |
            pr-automatizado
            a-ser-revisado